### ISSUE TITLE
OperationalError: no such table: cards

### ISSUE THREAD

**Issue by 0xasim** [jwasham/computer-science-flash-cards#38]
I am trying to run it on localhost on my ubuntu cosmic 18.10 cosmic, i've gone through each step but on runtime, here is the error i encounter

python flash_cards.py 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [16/May/2019 14:47:16] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2019 14:47:29] "POST /login HTTP/1.1" 302 -
[2019-05-16 14:47:29,148] ERROR in app: Exception on /cards [GET]
Traceback (most recent call last):
  File "/home/asim/Desktop/cards/CS-flash-cards/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/asim/Desktop/cards/CS-flash-cards/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/asim/Desktop/cards/CS-flash-cards/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/asim/Desktop/cards/CS-flash-cards/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/asim/Desktop/cards/CS-flash-cards/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flash_cards.py", line 76, in cards
    cur = db.execute(query)
OperationalError: no such table: cards
127.0.0.1 - - [16/May/2019 14:47:29] "GET /cards HTTP/1.1" 500 -
127.0.0.1 - - [16/May/2019 14:47:29] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by ckjeter** [comment]
how do you solve this problem?
